"""grundschema

Revision ID: 0001
Revises:
Erstellt: 2026-10-01 11:20:31.657354
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("modus", sa.String(length=20), nullable=False),
        sa.Column("standort", sa.String(length=200), nullable=True),
        sa.CheckConstraint(
            "modus IN ('bekleidung', 'werkzeug')", name="ck_automat_modus"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "einstellung",
        sa.Column("schluessel", sa.String(length=100), nullable=False),
        sa.Column("wert", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("schluessel"),
    )
    op.create_table(
        "mail",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empfaenger", sa.String(length=200), nullable=False),
        sa.Column("betreff", sa.String(length=200), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("versuche", sa.Integer(), nullable=False),
        sa.Column("letzter_fehler", sa.Text(), nullable=True),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("gesendet_am", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mitarbeiter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("personalnummer", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("abteilung", sa.String(length=100), nullable=True),
        sa.Column("aktiv", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("personalnummer"),
    )
    op.create_table(
        "recht",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schluessel", sa.String(length=50), nullable=False),
        sa.Column("beschreibung", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schluessel"),
    )
    op.create_table(
        "rolle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("bezeichnung", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "benutzer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=50), nullable=False),
        sa.Column("passwort_hash", sa.String(length=255), nullable=True),
        sa.Column("rolle_id", sa.Integer(), nullable=False),
        sa.Column("mitarbeiter_id", sa.Integer(), nullable=True),
        sa.Column("aktiv", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mitarbeiter_id"], ["mitarbeiter.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["rolle_id"],
            ["rolle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    op.create_table(
        "chip",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kennung", sa.String(length=64), nullable=False),
        sa.Column("technologie", sa.String(length=30), nullable=True),
        sa.Column("mitarbeiter_id", sa.Integer(), nullable=True),
        sa.Column("aktiv", sa.Boolean(), nullable=False),
        sa.Column(
            "angelegt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mitarbeiter_id"], ["mitarbeiter.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kennung"),
    )
    op.create_table(
        "io_modul",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("automat_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("treiber", sa.String(length=30), nullable=False),
        sa.Column("adresse", sa.String(length=100), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("di_invertiert", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["automat_id"],
            ["automat.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rolle_recht",
        sa.Column("rolle_id", sa.Integer(), nullable=False),
        sa.Column("recht_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["recht_id"], ["recht.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rolle_id"], ["rolle.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rolle_id", "recht_id"),
    )
    op.create_table(
        "fach",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("automat_id", sa.Integer(), nullable=False),
        sa.Column("nummer", sa.Integer(), nullable=False),
        sa.Column("io_modul_id", sa.Integer(), nullable=True),
        sa.Column("kanal", sa.Integer(), nullable=True),
        sa.Column("zustand", sa.String(length=20), nullable=False),
        sa.Column("gesperrt", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "zustand IN ('frei', 'belegt', 'gestoert')", name="ck_fach_zustand"
        ),
        sa.ForeignKeyConstraint(
            ["automat_id"],
            ["automat.id"],
        ),
        sa.ForeignKeyConstraint(
            ["io_modul_id"],
            ["io_modul.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("automat_id", "nummer"),
        sa.UniqueConstraint("io_modul_id", "kanal"),
    )
    op.create_table(
        "ereignis",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "zeitpunkt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("automat_id", sa.Integer(), nullable=False),
        sa.Column("art", sa.String(length=40), nullable=False),
        sa.Column("fach_id", sa.Integer(), nullable=True),
        sa.Column("chip_id", sa.Integer(), nullable=True),
        sa.Column("mitarbeiter_id", sa.Integer(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["automat_id"],
            ["automat.id"],
        ),
        sa.ForeignKeyConstraint(["chip_id"], ["chip.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["fach_id"], ["fach.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["mitarbeiter_id"], ["mitarbeiter.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ereignis_zeitpunkt"), "ereignis", ["zeitpunkt"], unique=False
    )
    op.create_table(
        "zuweisung",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fach_id", sa.Integer(), nullable=False),
        sa.Column("mitarbeiter_id", sa.Integer(), nullable=False),
        sa.Column("befuellt_von", sa.Integer(), nullable=True),
        sa.Column(
            "befuellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("abgeholt_am", sa.DateTime(timezone=True), nullable=True),
        sa.Column("storniert", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["befuellt_von"], ["benutzer.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["fach_id"],
            ["fach.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mitarbeiter_id"],
            ["mitarbeiter.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_zuweisung_offen_fach",
        "zuweisung",
        ["fach_id"],
        unique=True,
        postgresql_where=sa.text("abgeholt_am IS NULL AND NOT storniert"),
    )
    op.create_index(
        "uq_zuweisung_offen_mitarbeiter",
        "zuweisung",
        ["mitarbeiter_id"],
        unique=True,
        postgresql_where=sa.text("abgeholt_am IS NULL AND NOT storniert"),
    )
    # ### end Alembic commands ###
    _stammdaten()


# Rechte und Rollen gehören zum Programm, nicht zur Installation – daher in der
# Migration statt im Seed. Matrix laut CLAUDE.md, Abschnitt „Rollen“.
RECHTE = [
    ("fach_abholen", "Eigenes Fach abholen"),
    ("fach_befuellen", "Fach befüllen und zuweisen"),
    ("zuweisung_stornieren", "Zuweisung stornieren"),
    ("fach_oeffnen", "Fach manuell öffnen"),
    ("fach_sperren", "Fach sperren/entsperren"),
    ("chip_anlernen", "Chip am Automaten anlernen"),
    ("chip_verknuepfen", "Chip im Webinterface verknüpfen"),
    ("protokoll_lesen", "Protokoll einsehen"),
    ("mitarbeiter_verwalten", "Mitarbeiter verwalten"),
    ("benutzer_verwalten", "Benutzer verwalten"),
    ("einstellungen_verwalten", "Einstellungen ändern"),
]
ROLLEN = {
    "admin": ("Administrator", [r for r, _ in RECHTE]),
    "waesche": (
        "Wäscheabteilung",
        [r for r, _ in RECHTE[:8]],
    ),
    "mitarbeiter": ("Mitarbeiter", ["fach_abholen"]),
}
EINSTELLUNGEN = {
    "schloss.impuls_ms": "1500",
    "display.timeout_s": "60",
    "web.sitzung_min": "30",
    "protokoll.tage": "60",
    "erinnerung.tage": "5",
}


def _stammdaten() -> None:
    recht = sa.table(
        "recht", sa.column("id"), sa.column("schluessel"), sa.column("beschreibung")
    )
    rolle = sa.table(
        "rolle", sa.column("id"), sa.column("name"), sa.column("bezeichnung")
    )
    rolle_recht = sa.table("rolle_recht", sa.column("rolle_id"), sa.column("recht_id"))
    einstellung = sa.table("einstellung", sa.column("schluessel"), sa.column("wert"))

    recht_ids = {s: i for i, (s, _) in enumerate(RECHTE, start=1)}
    op.bulk_insert(
        recht,
        [{"id": recht_ids[s], "schluessel": s, "beschreibung": b} for s, b in RECHTE],
    )
    zuordnung = []
    for rolle_id, (name, (bezeichnung, rechte)) in enumerate(ROLLEN.items(), start=1):
        op.bulk_insert(
            rolle, [{"id": rolle_id, "name": name, "bezeichnung": bezeichnung}]
        )
        zuordnung += [{"rolle_id": rolle_id, "recht_id": recht_ids[r]} for r in rechte]
    op.bulk_insert(rolle_recht, zuordnung)
    op.bulk_insert(
        einstellung, [{"schluessel": k, "wert": v} for k, v in EINSTELLUNGEN.items()]
    )
    # IDs wurden explizit gesetzt → Sequenzen nachziehen, sonst kollidiert der
    # nächste normale INSERT.
    op.execute("SELECT setval('recht_id_seq', (SELECT max(id) FROM recht))")
    op.execute("SELECT setval('rolle_id_seq', (SELECT max(id) FROM rolle))")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_zuweisung_offen_mitarbeiter",
        table_name="zuweisung",
        postgresql_where=sa.text("abgeholt_am IS NULL AND NOT storniert"),
    )
    op.drop_index(
        "uq_zuweisung_offen_fach",
        table_name="zuweisung",
        postgresql_where=sa.text("abgeholt_am IS NULL AND NOT storniert"),
    )
    op.drop_table("zuweisung")
    op.drop_index(op.f("ix_ereignis_zeitpunkt"), table_name="ereignis")
    op.drop_table("ereignis")
    op.drop_table("fach")
    op.drop_table("rolle_recht")
    op.drop_table("io_modul")
    op.drop_table("chip")
    op.drop_table("benutzer")
    op.drop_table("rolle")
    op.drop_table("recht")
    op.drop_table("mitarbeiter")
    op.drop_table("mail")
    op.drop_table("einstellung")
    op.drop_table("automat")
    # ### end Alembic commands ###
